version: 2
jobs:
  cargo_fetch:
    docker:
      - image: inputoutput/rust:stable
    working_directory: /home/circleci/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-
            - cargo-v3-
      - run: cargo fetch
      - persist_to_workspace:
          root: /home/circleci/build
          paths:
            - Cargo.lock
      - save_cache:
          key: cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - /usr/local/cargo/git

  test_debug:
    docker:
      - image: inputoutput/rust:stable
    working_directory: /home/circleci/build
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/build
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build
          command: cargo build --tests --verbose --frozen
      - run:
          name: Test
          environment:
            RUST_BACKTRACE: 1
          command: cargo test --verbose --frozen

  test_release:
    docker:
      - image: inputoutput/rust:stable
    working_directory: /home/circleci/build
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/build
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build
          command: cargo build --tests --verbose --frozen --release
      - run:
          name: Test
          command: cargo test --verbose --frozen --release

  test_nightly:
    docker:
      - image: inputoutput/rust:nightly
    working_directory: /home/circleci/build
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/build
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build
          command: cargo build --tests --verbose --frozen
      - run:
          name: Test
          environment:
            RUST_BACKTRACE: 1
          command: cargo test --verbose --frozen

workflows:
  version: 2
  test_all:
    jobs:
      - cargo_fetch
      - test_debug:
          requires:
            - cargo_fetch
      - test_release:
          requires:
            - cargo_fetch
      - test_nightly:
          requires:
            - cargo_fetch
