[package]
name = "chain-network"
version = "0.1.0"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
async-trait = "0.1"
futures = "0.3"
pin-project = "0.4"
prost = "0.6"
thiserror = "1.0"
tonic = "0.1"

[build-dependencies]
tonic-build = "0.1"
